//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nulo.Modules.WorkspaceManager {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultWorkspaces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultWorkspaces() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nulo.Modules.WorkspaceManager.DefaultWorkspaces", typeof(DefaultWorkspaces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.25&quot; DockRightPortion=&quot;0.25&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.25&quot; ActiveDocumentPane=&quot;3&quot; ActivePane=&quot;3&quot;&gt;&lt;Contents Count=&quot;4&quot;&gt;&lt;Content ID=&quot;0&quot; PersistString=&quot;Nulo.Panels.LeftPanel&quot; AutoHidePortion=&quot;0.25&quot; IsHidden=&quot;False&quot; IsFloat=&quot;False&quot; /&gt;&lt;Content ID=&quot;1&quot; PersistString=&quot;Nulo.Panels.RightPanel&quot; AutoHidePortion=&quot;0.25&quot; IsHidden=&quot;False&quot; IsFloat=&quot;False&quot; /&gt;&lt;Content ID=&quot;2&quot; PersistString=&quot;Nulo.Panels.BottomPanel&quot; AutoHideP [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.25&quot; DockRightPortion=&quot;0.25&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.25&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;&lt;Contents Count=&quot;0&quot; /&gt;&lt;Panes Count=&quot;0&quot; /&gt;&lt;DockWindows&gt;&lt;DockWindow ID=&quot;0&quot; DockState=&quot;Document&quot; ZOrderIndex=&quot;1&quot;&gt;&lt;NestedPanes Count=&quot;0&quot; /&gt;&lt;/DockWindow&gt;&lt;DockWindow ID=&quot;1&quot; DockState=&quot;DockLeft&quot; ZOrderIndex=&quot;2&quot;&gt;&lt;NestedPanes Count=&quot;0&quot; /&gt;&lt;/DockWindow&gt;&lt;DockWindow ID=&quot;2&quot; DockState=&quot;DockRight&quot; ZOrderIndex=&quot;3&quot;&gt;&lt;NestedPa [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.25&quot; DockRightPortion=&quot;0.25&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.25&quot; ActiveDocumentPane=&quot;0&quot; ActivePane=&quot;0&quot;&gt;&lt;Contents Count=&quot;4&quot;&gt;&lt;Content ID=&quot;0&quot; PersistString=&quot;Nulo.Panels.LeftPanel&quot; AutoHidePortion=&quot;0.25&quot; IsHidden=&quot;False&quot; IsFloat=&quot;False&quot; /&gt;&lt;Content ID=&quot;1&quot; PersistString=&quot;Nulo.Panels.RightPanel&quot; AutoHidePortion=&quot;0.25&quot; IsHidden=&quot;False&quot; IsFloat=&quot;False&quot; /&gt;&lt;Content ID=&quot;2&quot; PersistString=&quot;Nulo.Panels.BottomPanel&quot; AutoHideP [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string FourSplit {
            get {
                return ResourceManager.GetString("FourSplit", resourceCulture);
            }
        }
    }
}
